FROM devopsedu/webapp

RUN apt update && apt install -y apache2

ENV APACHE_RUN_USER www-data
ENV APACHE_RUN_GROUP www-data
ENV APACHE_LOG_DIR /var/log/apache2
ENV APACHE_RUN_DIR /var/www/html

COPY website /var/www/html/

ENTRYPOINT ["/usr/sbin/apache2"]

EXPOSE 80
CMD ["-D", "FOREGROUND"]

